# Generated by Django 5.0 on 2024-08-22 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_image_event_thumbnail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="day",
        ),
    ]
