# Generated by Django 5.0 on 2024-08-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_remove_event_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
