# Generated by Django 5.0 on 2024-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="events",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="medals",
        ),
        migrations.AddField(
            model_name="myuser",
            name="current_active_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="myuser",
            name="max_consecutive_active_days",
            field=models.IntegerField(default=0),
        ),
    ]
