# Generated by Django 5.0 on 2024-08-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BadgesHIW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_link", models.URLField()),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Badges HIW",
                "verbose_name_plural": "Badges HIWs",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.CreateModel(
            name="GetStarted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_link", models.URLField()),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Get Started",
                "verbose_name_plural": "Get Started",
            },
        ),
        migrations.CreateModel(
            name="MentalHIW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_link", models.URLField()),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Mental HIW",
                "verbose_name_plural": "Mental HIWs",
            },
        ),
        migrations.CreateModel(
            name="PhysicalHIW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_link", models.URLField()),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Physical HIW",
                "verbose_name_plural": "Physical HIWs",
            },
        ),
        migrations.CreateModel(
            name="PrizesHIW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_link", models.URLField()),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Prizes HIW",
                "verbose_name_plural": "Prizes HIWs",
            },
        ),
        migrations.CreateModel(
            name="SocialHIW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_link", models.URLField()),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Social HIW",
                "verbose_name_plural": "Social HIWs",
            },
        ),
    ]
