# Generated by Django 5.0 on 2024-08-13 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("how_it_works", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="badgeshiw",
            old_name="image",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="getstarted",
            old_name="image",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="mentalhiw",
            old_name="image",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="physicalhiw",
            old_name="image",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="prizeshiw",
            old_name="image",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="socialhiw",
            old_name="image",
            new_name="thumbnail",
        ),
    ]
