# Generated by Django 5.0 on 2024-08-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.CreateModel(
            name="DailyPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="")),
                ("company_name", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=100)),
                ("prize_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("video_link", models.URLField()),
                ("ig_link", models.URLField(blank=True, null=True)),
                ("tiktok_link", models.URLField(blank=True, null=True)),
                ("twitter_link", models.URLField(blank=True, null=True)),
                (
                    "yt_link",
                    models.URLField(blank=True, null=True, verbose_name="Youtube link"),
                ),
            ],
            options={
                "verbose_name": "Daily Prize",
                "verbose_name_plural": "Daily Prizes",
            },
        ),
        migrations.CreateModel(
            name="Medal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Medal",
                "verbose_name_plural": "Medals",
            },
        ),
    ]
