# Generated by Django 5.0 on 2024-08-13 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prizes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Trophy",
                "verbose_name_plural": "Trophies",
            },
        ),
        migrations.AddField(
            model_name="dailyprize",
            name="app_store_link",
            field=models.URLField(blank=True, null=True, verbose_name="App store link"),
        ),
        migrations.AddField(
            model_name="dailyprize",
            name="day",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Challenge day"
            ),
        ),
        migrations.AddField(
            model_name="dailyprize",
            name="play_store_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Play store link"
            ),
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_awarded", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes_won",
                        to="prizes.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
            },
        ),
        migrations.CreateModel(
            name="UserMedal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_awarded", models.DateTimeField(auto_now_add=True)),
                (
                    "medal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes_won",
                        to="prizes.medal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_medals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Medal",
                "verbose_name_plural": "User Medals",
            },
        ),
        migrations.CreateModel(
            name="UserPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_code", models.CharField(max_length=100)),
                ("date_awarded", models.DateTimeField(auto_now_add=True)),
                (
                    "prize",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes_won",
                        to="prizes.dailyprize",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_prizes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Prize",
                "verbose_name_plural": "User Prizes",
            },
        ),
        migrations.CreateModel(
            name="UserTrophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_awarded", models.DateTimeField(auto_now_add=True)),
                (
                    "trophy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes_won",
                        to="prizes.trophy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_trophies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Trophy",
                "verbose_name_plural": "User Trophies",
            },
        ),
    ]
