# Generated by Django 5.0 on 2024-08-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prizes", "0002_trophy_dailyprize_app_store_link_dailyprize_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyprize",
            name="thumbnail_video",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
