# Generated by Django 5.2.11 on 2026-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prizes", "0003_dailyprize_thumbnail_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={
                "ordering": ["id"],
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.AlterModelOptions(
            name="dailyprize",
            options={
                "ordering": ["-id"],
                "verbose_name": "Daily Prize",
                "verbose_name_plural": "Daily Prizes",
            },
        ),
        migrations.AlterModelOptions(
            name="medal",
            options={
                "ordering": ["id"],
                "verbose_name": "Medal",
                "verbose_name_plural": "Medals",
            },
        ),
        migrations.AlterModelOptions(
            name="trophy",
            options={
                "ordering": ["id"],
                "verbose_name": "Trophy",
                "verbose_name_plural": "Trophies",
            },
        ),
        migrations.AlterModelOptions(
            name="userbadge",
            options={
                "ordering": ["-date_awarded"],
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
            },
        ),
        migrations.AlterModelOptions(
            name="usermedal",
            options={
                "ordering": ["-date_awarded"],
                "verbose_name": "User Medal",
                "verbose_name_plural": "User Medals",
            },
        ),
        migrations.AlterModelOptions(
            name="userprize",
            options={
                "ordering": ["-date_awarded"],
                "verbose_name": "User Prize",
                "verbose_name_plural": "User Prizes",
            },
        ),
        migrations.AlterModelOptions(
            name="usertrophy",
            options={
                "ordering": ["-date_awarded"],
                "verbose_name": "User Trophy",
                "verbose_name_plural": "User Trophies",
            },
        ),
        migrations.AlterField(
            model_name="badge",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="prizes/awards/files/"
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="prizes/awards/images/"
            ),
        ),
        migrations.AlterField(
            model_name="dailyprize",
            name="logo",
            field=models.ImageField(upload_to="prizes/logos/"),
        ),
        migrations.AlterField(
            model_name="dailyprize",
            name="thumbnail_video",
            field=models.ImageField(
                blank=True, null=True, upload_to="prizes/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="medal",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="prizes/awards/files/"
            ),
        ),
        migrations.AlterField(
            model_name="medal",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="prizes/awards/images/"
            ),
        ),
        migrations.AlterField(
            model_name="trophy",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="prizes/awards/files/"
            ),
        ),
        migrations.AlterField(
            model_name="trophy",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="prizes/awards/images/"
            ),
        ),
    ]
