# Generated by Django 5.0 on 2024-08-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Instructor name"),
                ),
                ("description", models.TextField()),
                ("ig_link", models.URLField(blank=True, null=True)),
                ("tiktok_link", models.URLField(blank=True, null=True)),
                ("twitter_link", models.URLField(blank=True, null=True)),
                (
                    "yt_link",
                    models.URLField(blank=True, null=True, verbose_name="Youtube link"),
                ),
            ],
            options={
                "verbose_name": "Instructor",
                "verbose_name_plural": "Instructors",
            },
        ),
        migrations.CreateModel(
            name="MentalChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Challenge day",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "voice_recording",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Mental Challenge",
                "verbose_name_plural": "Mental Challenges",
            },
        ),
        migrations.CreateModel(
            name="SocialChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Challenge day",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Social Challenge",
                "verbose_name_plural": "Social Challenges",
            },
        ),
        migrations.CreateModel(
            name="IntensePhysicalChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Challenge day",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "workout_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "required_equipments",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("video", models.URLField(blank=True, max_length=250, null=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.instructor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intense Physical Challenge",
                "verbose_name_plural": "Intense Physical Challenges",
            },
        ),
        migrations.CreateModel(
            name="ModeratePhysicalChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Challenge day",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "workout_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "required_equipments",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("video", models.URLField(blank=True, max_length=250, null=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.instructor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderate Physical Challenge",
                "verbose_name_plural": "Moderate Physical Challenges",
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Challenge day",
                    ),
                ),
                ("quote", models.TextField(blank=True, null=True)),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("video_link", models.URLField(blank=True, max_length=250, null=True)),
                (
                    "intense_physical",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.intensephysicalchallenge",
                    ),
                ),
                (
                    "mental",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.mentalchallenge",
                    ),
                ),
                (
                    "moderate_physical",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.moderatephysicalchallenge",
                    ),
                ),
                (
                    "social",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.socialchallenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
            },
        ),
    ]
