# Generated by Django 5.0 on 2024-08-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intensephysicalchallenge",
            name="thumbnail_mobile",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="intensephysicalchallenge",
            name="thumbnail_square",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="moderatephysicalchallenge",
            name="thumbnail_mobile",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="moderatephysicalchallenge",
            name="thumbnail_square",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
