# Generated by Django 5.0 on 2024-08-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0006_alter_challenge_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="thumbnail_video",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
