# Generated by Django 5.0 on 2024-08-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0007_challenge_thumbnail_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="intensephysicalchallenge",
            name="thumbnail_video",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="moderatephysicalchallenge",
            name="thumbnail_video",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
