# Generated by Django 5.0 on 2024-08-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0008_intensephysicalchallenge_thumbnail_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intensephysicalchallenge",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moderatephysicalchallenge",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
