# Generated by Django 5.0 on 2024-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0009_alter_intensephysicalchallenge_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intensephysicalchallenge",
            name="banner_desktop",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="intensephysicalchallenge",
            name="banner_mobile",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="mentalchallenge",
            name="banner_desktop",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="mentalchallenge",
            name="banner_mobile",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="moderatephysicalchallenge",
            name="banner_desktop",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="moderatephysicalchallenge",
            name="banner_mobile",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="socialchallenge",
            name="banner_desktop",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="socialchallenge",
            name="banner_mobile",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
